site_name: https://github.com/FrankLef/test1.git

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

nav:
  - index.md
  - Tutorials: tutorials.md
  - How-to Guides: how-to-guides.md
  - References: reference.md
  - Explanations: explanation.md
