tdict = "tdict.xlsx"

[db]
fn = "C:/Users/Public/MyAcctg/xbrl/db_xbr.accdb"

[raw_db]
fn = "C:/Users/Public/MyAcctg/xbrl/db_xbr.accdb"

[data_paths]
temp = "d0_temp"
extr = "d1_extr"
transf = "d2_transf"
load = "d3_load"
raw = "d4_raw"
preproc = "d5_preproc"
eda = "d6_eda"
final = "d7_final"
