duckdb = "todo.duckdb"

[bag]
sources = "bag_sources.xlsx"
schema = "bag_schema.xlsx"
output = "bag_output.xlsx"

[db]
xbr = "C:/Users/Public/MyAcctg/xbrl/db_xbr.accdb"

[dpaths]
setup = "d0_setup"
extr = "d1_extr"
transf = "d2_transf"
load = "d3_load"
raw = "d4_raw"
pproc = "d5_pproc"
eda = "d6_eda"
teard = "d9_teard"
