# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-case-conflict
        -   id: debug-statements
        -   id: detect-private-key
        -   id: check-merge-conflict
        -   id: check-added-large-files
        -   id: check-docstring-first
        -   id: name-tests-test
            args: [--pytest-test-first]
    -   repo: https://github.com/PyCQA/flake8
        rev: 6.1.0
        hooks:
        -   id: flake8
            args: [--ignore=E501]
    -   repo: https://github.com/psf/black
        rev: 23.12.0
        hooks:
        -   id: black
    -   repo: https://github.com/pycqa/isort
        rev: 5.13.0
        hooks:
        -   id: isort
            args: ["--profile", "black"]
