

[message]
main = "Processing the main flow."

# ms access database specs
[msaccess]
path = "C:/Users/Public/MyJob/DesjCap_cies/PHT/db_PHT_V1_xprt.accdb"
tables = ["tbl_xprt_sales_grp", "tbl_xprt_part"]
